# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  shoplaptopefcore:
    image: shoplaptopefcore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5200:5200
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
